jwt:
  secret: YlZ2JkU3pVZ0ZkY0pNd1BqZV9rTXdkdkpTTUVnQ2Y1U1VLMU1uUWtJQ1pKd1EySzN4dnFVR0Zz
  expirationMs: 3600000

internal:
  token: INTERNAL_SECRET_TOKEN

spring:
  datasource:
    username: root
    password: root
