server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/customer_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true

  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

customer:
  default:
    daily-limit: 10000000

jwt:
  secret: your_secret
  expirationMs: 3600000
