server:
  port: 8084

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tuanpaph35819@fpt.edu.vn
    password: zrzd olmd jvzq obwh
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

management:
  endpoints:
    web:
      exposure:
        include: prometheus
